### ISSUE TITLE
Android auto-rotation

### ISSUE THREAD

**Issue by AmanitaVerna** [nesbox/TIC-80#1263]
The Android version of TIC-80 auto-rotates between portrait and landscape despite auto-rotate being turned off, which seems like a bug, as it is doing the opposite of what the user wants.

**Comment by 2439905184** [comment]
I also have the problem . It makes it more hard to programe game.
And there is no virtual keyboard as before.
Now it changed to system keyboard.
but This key board can't always float on the top.
Maybe I have to use physics usb keyboard to programe.
I want to use the virtual keyboard before

**Comment by nesbox** [comment]
We are going to restore the virtual keyboard and give a user ability to select keyboard type.

**Comment by nesbox** [comment]
Keyboard issues fixed with #660

**Comment by nesbox** [comment]
It seems it's a bug on the SDL2 lib side, because we do nothing with the screen rotation on our side.
Also, I tried to update to `SDL 2.0.14` but without result.
Let's check the issue later with new sdl updates.

**Comment by nesbox** [comment]
The virtual keyboard has been restored, but I don't know how to check if auto-rotation is locked.
next version...

**Comment by Ezra** [comment]
As of version `1.0.2164 (b09c50c)`, I'm still getting unwanted auto-rotation. (But the keyboard switching is working pretty well.)

Some Internet sources seem to say that this would be set not in the SDL2 lib but in your Android manifest (`AndroidManifest.xml`), with the attribute `android:screenOrientation`, e.g. 

`<activity
    ...
    android:screenOrientation="unspecified"
    ...
/activity`
