### ISSUE TITLE
[Suggestion] Treat TIC()+SNC() and OVR()+BDR() as two different layers

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1632]
I'm extremely confused about how ```OVR``` and ```BDR``` should be used. It seems that ```OVR``` were implemented in the API to be able to do things like having a waving background while drawing the sprites correctly, but the way it work is odd, trying to poke things like the screen offset values do nothing at all. And for now ```BDR``` just do the same as ```SCN``` but with more lines, and nothing that were drawing during the ```OVR``` are affected by it.

My suggestion would be to make ```OVR``` and ```BDR``` act the same as ```TIC``` and ```SCN``` but as if it were a "second layer", so any poke'd values will not affect the "first layer".

Note: With ```OVR``` acting like ```TIC``` I'm only referring to rendering and vram access, just to make it completely clear.

**Comment by nesbox** [comment]
Agreed, good thoughts, let's do so.
Thank you.

**Comment by joshgoebel** [comment]
@nesbox Can you point me to the major work/PR/commits on `BDR` and give me some quick pointers on how it works?  We need to add it to the wiki.

**Comment by nesbox** [comment]
Pls look at 973dd00
You know, the screen resolution is 240x136, with the border it's 256x144.
So, the BDR(row) callback works the same as SCN(row) the only difference is it goes through the full TIC80 screen including the border from 0-143 row, while SCN() 0-135 row only.

**Comment by joshgoebel** [comment]
So why do we need both `BDR` and `SCN`??

**Comment by joshgoebel** [comment]
> My suggestion would be to make OVR and BDR act the same as TIC and SCN but as if it were a "second layer", so any poke'd values will not affect the "first layer".

@Weeppiko How would this be done, exactly?  There is only one single VRAM with 16kb... there is not VRAM enough for two different layers... poking to VRAM changes the values in VRAM - which would be displayed on the next `TIC`...  

Or does anything poked to VRAM during OVR/SCN just "disappear" after OVR/SCN as if it never happened?  That seems quite strange behavior for `poke` and RAM...

I'm not sure this has been fully thought out yet...

**Comment by joshgoebel** [comment]
>  but the way it work is odd, trying to poke things like the screen offset values do nothing at all. 

I had thought @nesbox fixed this... I originally filed this as a bug: https://github.com/nesbox/TIC-80/issues/1305

perhaps you're running an old version?

**Comment by nesbox** [comment]
@Weeppiko just wants to move `BDR()` callback after the `OVR()` stage and add handling of the screen offset values (now it handles only border color).

current callbacks sequence is `TIC()+BDR()+SCN() then OVR()`
will be `TIC()+SCN() then OVR()+BDR(with the screen offset handling)`

**Comment by joshgoebel** [comment]
I may just add a mention that there is a `BDR` and say it's "in flux" and link here...?

**Comment by Weeppiko** [comment]
> To me the correct behavior is that things poked into VRAM during OVR should be drawn to the actual screen after OVR finishes... (but they are still persistent in VRAM - the contents that used to be there will have been over-written).

@joshgoebel I think you got it wrong, `OVR` happens after `SCN`, My suggestion was that what was done during `TIC` + `SCN` can't be accessed during `OVR` + `BDR`, in the same way it happens with the palettes, you can't modify the `SCN` palette during `OVR` because both palettes are in the same address and can only be accessed during their respective phases. But just moving `BDR` to happens after `OVR` with the same possibilities as `SCN` (change screen offset and palette colors per scanline) would be enough for me.

**Comment by joshgoebel** [comment]
>  I think you got it wrong, OVR happens after SCN

_I don't think I was speaking about sequencing in my comments._  The bug before was that you couldn't poke to VRAM during `OVR` only draw using `pix` and other other API (since they were drawing to some type of "magic buffer"), this seemed obviously wrong and should have been fixed (see linked PR above).  Although I'm not sure how it was fixed since I haven't reviewed that PR carefully.  Making the actual API commands actually draw to VRAM during OVR would have been "correct" I think but that would probably have been a breaking change. (although perhaps not if you still kept a "dirty" map of which pieces of the screen had been drawn and still needed to be "overload".

@nesbox Could you weigh in here on how that was solved?  Is there still a magic "hidden buffer" that is drawn to during overlay?  How does that interact with writing directly to VRAM with `poke`? 

>  My suggestion was that what was done during TIC + SCN can't be accessed during OVR + BDR, in the same way it happens with the palettes

I don't even know how to parse "what was done".  _Writing to RAM should be writing to RAM_ - am I missing something?  Does the render process somehow wipeout/revert palette RAM automagically after SCN?  That seems very unusual/unexpected behavior to me if that is the case.

If you're suggesting two copies of the VRAM I think I'm against that - that's a pretty "MAJOR" hardware change.  Although `OVR` has always been "weird" in that it pretends that is supported internally without every explaining how or why.  I think we should go back and very carefully think about OVR and how it should work vs keep just bolting more and more changes on top of it to try and "fix" it's behavior.  _It should have an actual story with regards to the TIC RAM and hardware._

> you can't modify the SCN palette during OVR because both palettes are in the same address and can only be accessed during their respective phases. 

NOW this is sounding vaguely familiar.  There is the "hidden" OVR palette that doesn't exist in RAM (already a slight problem IMHO from a "hardware" perspective) and then is swapped in during OVR I suppose?  So perhaps it is as you say, that the palettes are "magically banked" between OVR and non-OVR...

And can easily imagine a reasonable story here, for example:

> The TIC "hardware" has 48 bytes of internal reserved RAM used exclusively for the Overlay palette.   During the `OVR` pass this RAM is mapped into the `PALETTE` address space (making it accessible to peek/poke, etc)... and after OVR concluded that memory is remapped to the regular `PALETTE` RAM.

If that's the story, this should probably be better documented on the wiki.  I'd love to hear a similar story for how `OVR` is suppose to existing in a fantasy hardware sense.  I really think we should have one to guide the decisions we're making there from a "hardware" perspective.

Just saying the same thing with regards to ALL of VRAM - that there is a whole 16kb of internal reserved RAM that the "hardware" magically swaps in and out is kind of a tall order IMHO.  If that's the story though we should document it and stick to it and make sure the behavior is consistent with that.

**Comment by Weeppiko** [comment]
> I don't even know how to parse "what was done". Writing to RAM should be writing to RAM - am I missing something? Does the render process somehow wipeout/revert palette RAM automagically after SCN? That seems very unusual/unexpected behavior to me if that is the case.

I thought it in the same way it happens with the `SCN` palette during `OVR`, it still exists somewhere and will still be rendered when the frame ends, but can't be accessed, so I thought if this is what happens with the palette, why not with all VRAM?

I can't speak from a "hardware" perspective because I don't have a deep knowledge about it, but from a user perspective that are actually trying to understand when, what and why I can or can't access something in VRAM during a specific moment, this is all just suggestions that I thought it would make things less confusing and inconsistent. But still, just making `BDR` happens after `OVR` is okay for me, but still weird that `SCN` and `OVR` palettes are only accessible during their respective phases.

**Comment by joshgoebel** [comment]
> but from a user perspective that are actually trying to understand when, what and why I can or can't access something in VRAM during a specific moment,

Exactly, that is the big question and quite confusing. :-)  I'd argue we've only gotten to this confusing state because we started doing too much "magic" instead of just focusing on 'this is hardware, how does it behave'...  ie, `OVR` never should have been added (as a feature) until there was a clear story for how it maps into the hardware, VRAM, etc...

>  I thought if this is what happens with the palette, why not with all VRAM?

That's one potential solution... but unless we add more address space it has the same flaw that you mention in your next though - that it's weird and confusing for the "hardware" to just magically swap out entire segments of RAM out from under the user.

> but still weird that SCN and OVR palettes are only accessible during their respective phases.

I think this is because we've "run out of VRAM"... I can't otherwise think of a great reason we couldn't just have both palettes always in RAM at the same time...

**Comment by joshgoebel** [comment]
@Weeppiko What actual graphical effect are you trying to accomplish that you can't now?  Maybe that would help me understand a bit better... or perhaps an example cartridge/program?

**Comment by Weeppiko** [comment]
The effect that I'm trying to accomplish is give the `OVR` the same effects that are possible to do on `SCN` for `TIC`, change the colors and screen offsets per scanline. I've discussed about this on discord, but most people just said to not use `OVR` and draw everything on `TIC`, but it will means that I will only be able to use `SCN` palette for everything instead of both `SCN` and `OVR` for Background and Sprites the way I planned.
![image](https://user-images.githubusercontent.com/88540876/140589682-dfc6fb7b-1a98-4d86-84c2-aa6e560045ac.png)
![image](https://user-images.githubusercontent.com/88540876/140589718-cf370be2-bc9b-4147-a5f7-4febea3c9965.png)
![image](https://user-images.githubusercontent.com/88540876/140589726-80888f29-924d-4cc6-af1e-10bcdbeb0625.png)

**Comment by Weeppiko** [comment]
As I mentioned before, make `BDR` to happen after `OVR` will pretty much solve this issue for me

**Comment by joshgoebel** [comment]
> make BDR to happen after OVR will pretty much solve this issue for me

I'm interesting in how close we can get as things stand now.  Let me try to help now that I'm in a loop a bit more. :-)

> I've discussed about this on discord, but most people just said to not use OVR and draw everything on TIC, but it will means that I will only be able to use SCN palette for everything instead of both SCN and OVR for Background and Sprites the way I planned.

No, you can use a different palette for every single scanline...https://github.com/nesbox/TIC-80/wiki/SCN#example

So far in all these snaps above I don't see any reason you need OVR at all... I'm on Discord if chatting would be easier.

**Comment by joshgoebel** [comment]
Are you trying to use 32 colors on a single line and is your largest issue then that the SCREEN OFFSET behavior "doesn't work" properly inside OVR?

**Comment by Weeppiko** [comment]
>  `OVR` would only be needed if you need 32 different colors per scanline (drawing from both the `TIC` and `OVR` palettes)

This is pretty much what I want, I'm currently using the 16 colors from `SCN` exclusively made for Tiles/Background, and 16 colors from the `OVR` exclusively for Sprites.

But now here is the issue, for things that are drawing during `TIC`, it is possible to make changes per scanline, this is how this wavy and blue water effect is achieved, but it's impossible to do the same for things that are drawing during `OVR`. I can't make any change to it per scanlines because both `SCN` and `BDR` happens before it. I can't make any type of distortion effect to `OVR`, I can't change it's colors per scanline, etc.

**Comment by joshgoebel** [comment]
Yeah, I think this is just a desire that doesn't fit how OVR works [or is intended to] - at least in my understanding of it's intent.  I'm also not sure it should be changed without a lot more thought put into it.  _There are other ways to do what you want, with a little more elbow grease._ 

I still think of OVR as "overlay" (I know we changed the name)... it's a simple way to add a HUD or status bar or some *stationary* overlays on top of the existing screen... and (for convenience) you get a new palette.  That's how I've always understood it's utility... it's not (currently) a "second layer" intended for use in parallax or other complex graphics setups. 

![image](https://user-images.githubusercontent.com/6473/140591960-932a3b0d-c81e-4f26-a08f-2a6d20a72e67.png)

For example you might use it for something like the blue "status" boxes in the above (without the cool transparency)... As it stands now OVR is really just a fancy way to mask a different palette onto the "hardware" screen. (see my thoughts in my large OVR thread)

---

> I'm currently using the 16 colors from SCN exclusively made for Tiles/Background, and 16 colors from the OVR exclusively for Sprites.

So you can do this already.  You can have 16 TIC colors (per scanline) and 16 (total) OVR colors... so a max of 32 per line, but only 16 of those variable (those in the TIC/SCN loop)... I think you should consider doing the per-line distortion in software rather than "hardware"... ie, draw the screen as normal in `TIC` and then (at the end of TIC) go back and apply the desires shift to every line.  

If you're drawing the sprites in `OVR` and ALSO want them line shifted... that's quite a bit more complex (you need custom sprite rendering functions)... :-)   If your sprites don't need to be shifted then your'e home free.

**Comment by Weeppiko** [comment]
> I still think of OVR as "overlay" (I know we changed the name)... it's a simple way to add a HUD or status bar or some stationary overlays on top of the existing screen... and (for convenience) you get a new palette.

That is not really what was implied here on #429 when OVR was added to the API.

**Comment by joshgoebel** [comment]
I do think it *might* have made sense to have OVR respect the OFFSETS if we'd thought about it at the time. :-)  Since you could always set the offsets to 0 if you just wanted a flat overlay.

> That is not really what was implied here on #429 when OVR was added to the API.

I feel like perhaps we're talking past each other a bit... I didn't say "don't draw sprites in OVR"... The example given at that time _still works just fine_ - but when I look at it I see it proving my point.  The takeaway being that the sprite is *overlaid* on top of "all the other mess" - therefore purposely avoiding all the complexity in the TIC:

- avoiding offsets
- avoiding palette shifts

Intentionally.

**Comment by joshgoebel** [comment]
So back to your proposal... I think border was intended to change the border color... isn't what you want really just a second SCN pass, say if we had a two-stage SCN:

```
-- FRAME BEGINS (60 FPS)

   TIC()
   SCN(0) SCN(1) ... SCN(134) SCN(135)
   OVR()
   SCN(0, :ovr) SCN(1, :ovr) ... SCN(134, :ovr) SCN(135, :ovr)

-- FRAME END
```

You're just suggesting we repurpose it because it happens to be already laying around?  I purposely left out BDR because I think technically it could come anytime after `TIC` if all it does is paint the border area... and we're not repurposing it as a second SCN callback...

**Comment by Weeppiko** [comment]
Yeah, I understand, but for now, we have two scanlines functions happening one right to another without a good reason for it, they do almost the same thing, so it makes sense to put `BDR` to happen after `OVR` to at least give the user the option for do this sort of effect past `OVR` instead of arbitrarily left it as a limitation

**Comment by joshgoebel** [comment]
> instead of arbitrarily left it as a limitation

Of course we have lots of arbitrary limitations, just because we like them. :)

**Comment by Weeppiko** [comment]
So `BDR` just does the same as `SCN` but including the border color? Doesn't this means that `SCN` is somewhat redundant?

**Comment by joshgoebel** [comment]
> So BDR just does the same as SCN but including the border color? Doesn't this means that SCN is somewhat redundant?

AFAIK... BDR just provides a callback to do a palette swap that ONLY applies to the border.  (and touches border only scanliness)... it's hard to do this properly with SCN.

**Comment by joshgoebel** [comment]
I feel like OVR only was added because we lack "sprite hardware" like in older systems where the sprites were drawn by special parts of the video chip and hence had their own palettes, etc... I imagine people were having difficulty doing "cool stuff" with all the various effects (palette swaps, screen offset, etc) because it would entirely "mess up their sprites" (which wasn't desired at the time)... so we added OVR as sort of an equivalent to "hardware sprites".

**Comment by Weeppiko** [comment]
> AFAIK... BDR just provides a callback to do a palette swap that ONLY applies to the border.

That's not true, I can do that same water effect by using `BDR`. The only difference I can see between them is that `BDR` just include the vertical lines at the top and bottom of the screen and each of these lines can be changed, but `SCN` also does change colors for this lines when the first and last line are modified, but not for each one of them.

**Comment by joshgoebel** [comment]
> I can do that same water effect by using BDR.

You could, unless you wanted a DIFFERENT palette for the border vs the screen area.  Then you'd need both or you have a really ugly dance about where you have to set the next frames early border in the very last callback of SCN, it's messy.

**Comment by joshgoebel** [comment]
Or maybe I'm confused.  This was never documented in the wiki so I'm left just staring at the source.  Perhaps I need to whip up a quick test.

**Comment by Weeppiko** [comment]
Again, `SCN` does affect the border
![image](https://user-images.githubusercontent.com/88540876/140593709-25406142-3904-425e-89e8-46dc1f898f66.png)

**Comment by joshgoebel** [comment]
**Yes, I never said it didn't.**

**Comment by Weeppiko** [comment]
If you try to use both, `BDR` completely replaces any changes that was done during `SCN`

**Comment by joshgoebel** [comment]
> If you try to use both, BDR completely replaces any changes that was done during SCN

So you're right - you can't actually use them together as I would have expected.  This aspect seems buggy to me. :-)  Now i'm understanding why you're asking about duplication...

**Comment by joshgoebel** [comment]
What I was assuming:

- BDR called
- BDR painted (left and right)
- SCN called
-  middle of row painted

The reality:

- SCN called
- BDR called
- BDR painted (left and right)
-  middle of row painted

**Comment by Weeppiko** [comment]
> I feel like OVR only was added because we lack "sprite hardware" like in older systems where the sprites were drawn by special parts of the video chip and hence had their own palettes, etc... I imagine people were having difficulty doing "cool stuff" with all the various effects (palette swaps, screen offset, etc) because it would entirely "mess up their sprites" (which wasn't desired at the time)... so we added OVR as sort of an equivalent to "hardware sprites".

Except they also does this sort of things with sprites... I mean, just look at Sonic from Master System, it does have palette swaps for sprites during scanline in that water level, look at the life counter at the bottom of the screen how sonic faces is kind of green but sonic itself is not, and both of them are sprites
![image](https://user-images.githubusercontent.com/88540876/140593909-5e562f6c-1d40-457a-9550-540b68e73298.png)

**Comment by joshgoebel** [comment]
*I never said it was never done or never desirable.*  Only that at the time it obviously wasn't considered. :-)

**Comment by Weeppiko** [comment]
Yeah, but still, if `BDR` are changed to happen after `OVR` this will be something possible to do now, and it won't feel that `SCN` and `BDR` just does almost the same how it feels they currently do, that was my point.

**Comment by joshgoebel** [comment]
**Yeah, I see your point now.** :-)  It's very strange now, for sure.

Perhaps sometimes things are added without enough thought and discussion.  `BDR` might be a good example of this as it seems now you don't really need SCN at all...? and I'm pretty sure that wasn't the intent.  That's what I want to avoid us doing again.  I just want us to think it all thru very well this time and if we're going to change it again hopefully we get it 100% right the second time. :-)

**Comment by nesbox** [comment]
So, since we have **vram banking** and we can change **vbank** for each scanline, I think the issue can be closed.
Thank you all for your helpful thoughts.
