### ISSUE TITLE
Discussion: OVR needs a rethink, it makes no "hardware" sense 

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1660]
OVR feels very "bolted" on and like we're just pulling stuff out of a hat.  I think some thought needs to go into how it works and see if we can course correct - or if we care (though I'd be sad if we don't as to me this is taking a step away from a fantasy hardware console it's just fantasy in general).  I feel like the decisions being made with regard to OVR are very different than prior decision made and it's muddling the platform.

**TIC-80 feels like a real fantasy computer underneath, that's part of it's charm**

The rest of the platform behavior feels very "rooted in [fantasy] hardware" for the most part... what does `pix` do?  It writes to VRAM... **you can implement your own `pix`** - you don't have to use the system one, etc...  The audio state exists in RAM.  The palette exists in RAM.  The mouse state exists in RAM.  Underneath the API is "real" fantasy "hardware".  The API is merely interacting with the hardware.

Meanwhile, `OVR` is complete voodoo that violates all this...  For example:

- If I draw a `line` in OVR it seems to "disappear" come the next frame? 
  - How? why?  
  - Was it not written to VRAM?
  - If not, how did it get painted to the screen at all?
- Yet, if I poke two pixels in OVR they are persistent forever.

So, the question:

How would I write my own `line` function that has the same behavior the internal line function?  IE (in hardware terms) I want to write to the `OVERLAY` RAM - so that my line only persists during the overlay phase - just like the built in `line`.   In the past that has always been possible - writing functions to replace the internal API - because underneath it all was just the RAM/VRAM/magic memory register locations, etc...

---

**OVR is a violation of the fantasy computer aspect**

OVR is step off the path and I'd love to see if there is any way to fix this and get us back on the path.  If there is truly hidden OVR RAM - and that's the hardware explanation, then we should expose it as VRAM and make the machine a 112kb machine... I realize the memory map is "full", but there is  no reason it can't be expanded at the top-end... OR that a more manual "banked" approach couldn't be taken to VRAM the same as is taken with the other areas of cartridge "ROM".

For example, allow, VRAM banking:

```lua
vbank(0) -- default VRAM
vbank(1) -- OVR VRAM (contents are drawn overtop of default VRAM)
-- OR
VRAM = 1 << 8 -- bitmask for VRAM banking
sync(VRAM, 0) 
sync(VRAM, 1) 
```

Then the hardware story could be that there is 32KB of VRAM... accessible in two banks.  `OVR` and `TIC` could "magically" tickle the "hardware" such that the appropriate bank is addressed at the right time, etc... so now if I want to write a `line` function that draws only to OVR then I just `poke` into the OVR VRAM bank (1)... it's very clear how the "hardware" is working - no more magic.

I'm not saying this is perfect solution (the transparency aspect of OVR VRAM would be an open question).  I'm just trying to point out the problem, shed some light on it, and start a discussion about making this all make more sense in the future.

---

**Summary**

Again the key question here (which should have an answer from a hardware perspective):

> How would I write my own `line` function that has the same behavior the internal `line` function during `OVR`? (ie, how do I write directly to OVR buffer, but NOT the screen buffer using the hardware, not the API)

And questions for thought:

- Should the API be allowed/able to do things that are impossible to do by poking/peeking the RAM directly?
- If so, when is this allowable and when should it be discouraged?

If/when the core TIC API could be entirely replaced by peek/pokeing the "hardware" I'd say we've achieved a very high fidelity of being a real "fantasy computer" under the covers - which I've always felt was a key goal of the project (am I wrong?).  The less this holds true the more we become just a "gaming platform/engine" like https://domeengine.com and less of a "fantasy computer".

---

**An analogy how how I feel like lost the path with OVR**

Silly example: lets say we decided to add a "high res" mode that 480x272 or a "high color" mode (256 colors)...  you could do this two ways:

- Rethink the memory layout, increasing addressable VRAM to 32kb or 64kb to allow for more data
- Just say "it's magic, high res mode doesn't use VRAM just use the API functions instead"... ie, peek and poke become meaningless. The idea that it's "real hardware" under the surface becomes meaningless. There is no attempt to explain how "high res" or "high color " mode actually functions _with respect to the underlying fantasy hardware._

The latter is what I feel we've done (so far) with OVR and what I'd love to see course corrected.

---

> you can't modify the SCN palette during OVR because both palettes are in the same address and can only be accessed during their respective phases. 

NOW this is sounding vaguely familiar.  There is the "hidden" OVR palette that doesn't exist in RAM (already a slight problem IMHO from a "hardware" perspective) and then is swapped in during OVR I suppose?  So perhaps it is as you say, that the palettes are "magically banked" between OVR and non-OVR...

One can easily imagine a reasonable story here, for example:

> The TIC "hardware" has 48 bytes of internal reserved RAM used exclusively for the Overlay palette.   During the `OVR` pass this RAM is mapped into the `PALETTE` address space (making it accessible to peek/poke, etc)... and after OVR concluded that memory is remapped to the regular `PALETTE` RAM.

If that's the story, this should probably be better documented on the wiki.  I'd love to hear a similar story for how `OVR` is suppose to existing in a fantasy hardware sense.  I really think we should have one to guide the decisions we're making there from a "hardware" perspective.

Just saying the same thing with regards to ALL of VRAM - that there is a whole 16kb of internal reserved RAM that the "hardware" magically swaps in and out is kind of a tall order IMHO.  If that's the story though we should document it and stick to it and make sure the behavior is consistent with that.

_Originally posted by @joshgoebel in https://github.com/nesbox/TIC-80/issues/1632#issuecomment-960419302_

**Comment by Weeppiko** [comment]
I really liked the VRAM banking approach, and if it lets the user to change the bank anytime in the code, it can simply replace `OVR` entirely, just `TIC` and `SCN` would be needed in that case, for example:
```lua
function SCN(l)
	vbank(0)
	poke(0x03FF9,l)
	vbank(1)
	poke(0x03FF9,l)
end
```

For transparency, it can simply do the same as the old consoles like the Sega Master System does for example, where the first color of the sprite palette is always treated as transparency.

**Comment by joshgoebel** [comment]
>  where the first color of the sprite palette is always treated as transparency.

Or you could have a `OVR TRANSPARENCY` register - so any (or multiple) of the 16 colors could be treated as transparent...

>  it can simply replace OVR entirely,

Indeed it could, as all OVR would then become internally is essentially:

```
function OVR_dispatch()
  vbank(1) -- OVR VRAM
  OVR()
  vbank(1) -- default VRAM
end
```

This could also be fun in that it could allow users to build more abstractions on top, such as double buffering, etc...  switching from video banks at their own discretion, whenever they pleased... such as a game running at 30 FPS and taking two full frames to render the next frame (to a different video bank) and then when ready copying that DATA (or just perhaps touching a register that changes how the video banks are drawn to the screen).  To me that sounds like lots of opportunities for fun hardware hacking vs the "magic" we have now.

One downside to banks is there is no super fast way to copy from one bank to another (if you can only access one at a time)... but perhaps that would be largely mitigated if you had a register allowing you to swap banks at will.

**Comment by joshgoebel** [comment]
One thought is right now I'm don't think the "OVR RAM" is persistent... ie, it starts empty at every frame... I'm not sure that is a reasonable default if we went this direction (making it persistent RAM)... it probably should persist and then if someone wanted a clean OVR each time they could just call `cls` first to clear what was previously there. 

In saying that I'm assuming all the drawing commands would work on whatever the currently active `vbank` was.

**Comment by Weeppiko** [comment]
I'd expect it to be persistent, if the user wants to clear it then it need to be done manually. For example, if the `OVR` are being used for HUD elements, it could be done by checking what was changed in the game, then using both `clip` and `cls` to clear only that part of the screen and redraw it instead of redrawing everything every frame.

**Comment by Weeppiko** [comment]
I was checking the VRAM layout, and start to think if instead of creating another register for the `OVR TRANSPARENCY` why not just reuse the `BORDER COLOR` register? So it will be the border color for the `TIC` and transparency for `OVR` in the same address, instead of creating another register that will be used by only one of them.

**Comment by joshgoebel** [comment]
Well, for one is the border truly irrelevant in overlay?  One might assume I could poke the palette and change the color of the border in overlay... and what effect might this have with shifting the screen, etc? Could the overlay border have a different offset than the main border? ... but I'm not sure this is 100% relevant either...

I think perhaps you're exploring the idea that perhaps the "registers" at the top of VRAM might be distinct between bank 0 and 1... ie the entire 16kb is swapped out (allowing 64 bytes of new "registers"), not just the actual SCREEN data...  of course OVR palette and mappings are going to take 48 + 8 of that right off the bat... so that only gives you 8 new bytes to play with...

**Comment by joshgoebel** [comment]
> So it will be the border color for the TIC and transparency for OVR in the same address

Or now I'm realizing perhaps you meant the high and low nibble since (if we only allow a single transparent color) then that only requires 4 bits, and only 4 bits are currently used by border color, so technically half that register is free - even without any type of banking.

**Comment by Weeppiko** [comment]
I was actually talking about the same nibble, but I also didn't realize that it doesn't use the entire byte.
> I think perhaps you're exploring the idea that perhaps the "data registers" at the top of VRAM might be distinct between bank 0 and 1... ie the entire 16kb is swapped out (allowing 64 bytes of new "registers")

That is what I imagined it to be with the `vbank`, because it won't be need to change nothing in the VRAM layout since only one can be active. Both banks will use the same layout and addresses, but every change will happen only in the bank that are currently active. With this in mind, this is why I mentioned the `BORDER COLOR` can be reused for transparency, since in this context two `BORDER COLOR` registers will exist, one for each bank. The will happen with the `MOUSE CURSOR` register, it could be used as a mouse register for the second bank and something else for the first.

**Comment by Weeppiko** [comment]
It may sound like "magic" in the same way the `OVR` palette currently works, but if it's really a problem, then a part of the free ram at end can be used for VRAM banking, so when `vbank` is called it just swaps between then, so any VRAM bank can be accessed, even if it's not the active one, but it keeps the original layout to the active one.

**Comment by joshgoebel** [comment]
> It may sound like "magic" in the same way the OVR palette currently works,

Those things are quite a it different I think...the OVR palette STILL exists in RAM, just [technically] banked RAM - RAM that's only accessible during OVR - _I can still peek and poke it - at the right time_.  So technically there is already banked VRAM, just only ~56 bytes or so.  That's very different than the "magic" of how OVR currently works - which never exists in RAM at all (so far as I can tell)?

The problem (restated as perhaps a better example):

Lets say I have a custom bitblitting routine (using `poke` to VRAM) that I'm using in `TIC`... and then I decide that I'd like to use it in `OVR` to draw as an overlay... this should be a trivial copy/paste, but this is currently impossible (AFAIK) because the "overlay" is magic - it doesn't exist ANYWHERE in the hardware/RAM - so there is no way for a routine to write [poke] to it directly.  That is what I think needs to be resolved.

> then a part of the free ram at end can be used for VRAM banking

There isn't enough RAM at the end... though I suppose you could half-bank or some such... anyways I think people needing to copy between banks of VRAM might be an edge case anwways (provided we allowed page flipping in the design)...

**Comment by joshgoebel** [comment]
Oh I'd be remiss if I didn't point out that `SCREEN` (not all of VRAM, just screen) is already bankable as of latest versions. (although with the same bank switching limitations as exist for all bank switching - once per frame per segment) https://github.com/nesbox/TIC-80/wiki/sync

Though this has nothing to do with OVR or anything... I think it was a convenient way to [save the screenshot](https://github.com/nesbox/TIC-80/wiki/TIC-File-Format#screen) for the cartridge (in bank 0).

**Comment by nesbox** [comment]
> How would I write my own line function that has the same behavior the internal line function?

It's just a bug that is fixed in the dev version, the `line()` works the same in both `TIC()` and `OVR()` now, and this applies to all other screen API, also, you can peek()/poke() any pixel in VRAM during OVR.

---

Anyway, the idea of the bank switching VRAM is not bad. I see it as a cartridge that has an additional chip to extend the capabilities of the computer hardware (like NES did with MMC) and you can switch between them using `sync()` API or just poking register in VRAM. I'll even try to implement something one of these days and check how it will work.

The biggest question I have at the moment, as usual, is backward compatibility, I really don't want to add versioning and implement two different versions of screen renderers :(

**Comment by joshgoebel** [comment]
> the line() works the same in both TIC() and OVR() now, 

Not what I was asking.  I was asking:

> How do I write my own _custom_ line function that only draws to the "secret" OVR buffer?

IE, I want my changes to be non-persistent (just like the built-in `line` or other APIs)... so that if I don't draw them on the next frame, they magically disappear...

>  you can peek()/poke() any pixel in VRAM during OVR.

Yes, I know we fixed that bug, but that doesn't solve my problem... since changes to VRAM are persistent.

---

> or just poking register in VRAM.

That would have been my choice, but you just used them all with `CLIP`. 😜

And to answer my own question (if we had a register that switched between OVR and "regular") I'd just tickle that register, then write my line to VRAM (which would then be written to OVR), then untickle the register (or else the register would already be tickled by `OVR` itself)...

> backward compatibility, I really don't want to add versioning and implement two different versions of screen renderers

I'll give that some thought - I certainly understand... the problem right now is that my "dual buffer" proposal would likely require a transparent color for the layering... so you'd only have 15 colors to draw with, which would be one change from the current "magical" OVR where you're just keeping track of all the transparency internally.

**Comment by joshgoebel** [comment]
I believe my understanding has improved now.  I didn't realize how significantly the functionality here was changed when my OVR bug was fixed.  I think that fix resolves many of my issues with how OVR worked before (and invalidates a lot of the above) - so I'm no longer convinced we **need** immediate changes. :-)

_Speaking from a hardware story perspective this is what I see now:_

It seems as if OVR is masking "hardware"... One might imagine it was a 32,640 bit mask in the GFX hardware - even if not directly addressable. It provides a "masking" layer over the entire screen when in 'OVR' mode... any writes to VRAM now additionally modify that bitmask - such that when the screen is finally painted the mask determines whether the normal palette or the OVR palette is applied.  This feels better (than before) because while technically this "masking RAM" isn't directly addressable it can easily be written to _indirectly_:

```
-- toggle the OVR bitmask for a single pixel
poke4(0, peek4(0))
pix(0,0,pix(0,0))
```

This could probably even be done in large chunks with `memcpy` (copying memory over itself).  A bit strange, but it does provide indirect access to the masking system.  Say if someone wanting to have a rect that just moved around the screen and changed the palette "under it" wherever it went...

If someone is still thinking of it simple as an "overlay" layer and just draws entirely different things - that also works just fine... *with the caveat being that those changes are "flattened"/persisted in VRAM now* since there is no more hidden OVR buffer.  This forces someone to re-draw the screen fully in their `TIC` since changes they make in `OVR` are now permanent.  That's slightly different behavior than before, though I don't think it's necessarily a bad thing.

**Comment by nesbox** [comment]
Thank gods, I'm very happy :)
Anyway, I'm still going to test the idea with `sync(VRAM)` next week.

**Comment by joshgoebel** [comment]
VRAM sync isn't that useful IMHO unless it skips the per-frame limitation completely (since you'd most often want to draw to both "layers" in a single frame).  I imagine a common use case would be the same way we use OVR now:

```
vramSync(0)
-- draw background (VRAM0)
vramSync(1)
-- draw sprites to OVR "layer" (VRAM1)
```

I suppose you could get around this by saying it only syncs "magically" inside the OVR callback... and that if you sync it manually now you're suck waiting... but then I'd be forced to ask how come the hardware can do it so fast for OVR but when you request it manually it's SOOOO slow?

This is why I always invented a few API call rather than overloading the very busy already `sync`... I personally think from a hardware perspective this is [or should be] VERY different than `sync`.  We're not swapping ROM/EPROM from the cartridge into RAM... we'd literally have two VRAM segments in the hardware (32kb now, not 16kb) and we can choose which one to 'map" into the 0-16kb address space...

This is also starting to relate to some elements of the memory mapping discussion we're having regarding fantasy CPUs...

**Comment by nesbox** [comment]
I added `vbank(bank)` API here a6b4b7e.
We have **2x16K** VRAM chips now and can switch between them on the fly.
```lua
function TIC()
	vbank(1)
	-- draw to 2nd VRAM chip (OVR)...
	vbank(0)
	-- draw to default VRAM chip...
end
```
If you want to emulate the previous OVR behavior callback call:
```lua
function myOVR()
	-- ...
end

function TIC()
	-- ...
	vbank(1)
	cls()
	myOVR()
end
```
Of course, I left the `OVR()` callback for backward compatibility with old carts.

**Comment by nesbox** [comment]
Also, the sequence of graphic functions calling looks like `TIC() -> OVR() -> SCN(136)/BDR(144)` now.

**Comment by joshgoebel** [comment]
Oh, so THIS is why you have `cls`, clear the mask, this use case - well and I guess because its "hidden" you need some API to clear it...  Did you consider just having an optional flag to `vbank`:

```
vbank(1, true)
```

I really feel mixing this up with `cls` is a bit weird and confusing...

**Comment by joshgoebel** [comment]
So are we left with the "magic mask" for legacy behavior?  Did you consider just making a color of the second layer transparent instead - removing the need for the mask entirely?

**Comment by nesbox** [comment]
> Would it be so bad if it just auto-cleared every single TIC?

If you use the `OVR()` callback it automatically cleans the layer, it's for compatibility as usual, but if you use `vbank()` you can control the screen cleaning process manually.

**Comment by nesbox** [comment]
> So are we left with the "magic mask" for legacy behavior?

Unfortunately, yes, I don't see any other normal solution atm to support old carts, the transparent color of the second layer doesn't solve the issue :(

**Comment by joshgoebel** [comment]
> If you use the OVR() callback it automatically cleans the layer

Where is this done?  All I see in `core` is that bank is called then a grammars defined `overline` callback (which calls cls)... is this repeated inside every single grammar?  I wonder if it could be refactored to a single location.

**Comment by nesbox** [comment]
Suddenly VBANK and OVR now work without MEMMASK, I checked most of the popular games on the tic80.com website, seems all is ok, pls let me know if someone finds a broken cart.
`0x03FF8 (BORDER)` - transparent color for VBANK1 as you proposed.

**Comment by joshgoebel** [comment]
This is quite clever, but please let me confirm that now we have TWO distinct registers:

- Bank 0 : `0x03FF8` (BORDER) - TIC-80 BORDER color 
- Bank 1 : `0x03FF8` (VBANK1 TRANSPARENCY) - transparent color for VBANK1 

So there is now a single border color (in bank 0) and a single transparent value (in bank 1).  Yes?

**Comment by nesbox** [comment]
yep, I confirm it :)

**Comment by joshgoebel** [comment]
But now this is no longer true, didn't cd9023959117a55726bba2aeef3500dd1231ad45 just break?

```
vbank(0)
poke(0x03FF8,2)
```

I should be change the border color, but I can't know since I can't known which bank `tic_core_blit_ex` thinks is 0 and 1... they might be reversed... this seems problematic if the registers in each have different meaning...

**Comment by nesbox** [comment]
You can call `vbank() -> bank` to know current vbank.

**Comment by joshgoebel** [comment]
> You can call vbank() -> bank to know current vbank.

I think I was saying it's _too tightly coupled_ and therefore hard to reason about... two parts of the code can't work independently (as they easily could before).  For example this worked before:

```
-- some routine sets the border color PERIOD
-- because we can be certain it's in vbank0
function setBorder()
  vbank(0)
  poke(0x03FF8,2)
end

-- some other routine does fancy things with bank switching
vbank(..)
-- ...
vbank(..)
-- ...
vbank(..)
```

The border color is always set properly.  

---

After this change though these two piece of code must be tightly coupled/dependent, yes?... _there is no way for `setBorder` to know which bank to write to_ **without knowledge of bank switching that might happen later**.  It can't even ASK for the current bank as you suggest - because it doesn't matter what the CURRENT bank is then, it only matters what the current bank will be in the future... it only matters what the current bank is at the end of TIC, yes?

This seems like a regression to me, but I'm not sure what to suggest.  If this is how it stays I think the API is perhaps confusing... I think `vswap` would better...

If the registers between vbank0 and bank1 aren't the same (they aren't now since one holds border and the other holds the transparency byte) then those registers shouldn't "magically move/swap" whenever I switch banks... this is very confusing and I think it will be very confusing to document as well.  It means I can NEVER write a function to set the border color _without knowing about the entire under pipeline of the rest of the program_ (ie, which bank will be which at the end of TIC), and that strikes me as very bad.

True, if one is "careful" this all works out... but again I fear it's hard to explain, hard to document, etc... I think if these are the only two choices I might prefer the prior less magical arrangement where vbank1 was always on top.

That's my 0.02.

**Comment by nesbox** [comment]
> I think vswap might better

You might be surprised, but this is how it works internally, we swap two banks
https://github.com/nesbox/TIC-80/blob/4bda8f1f8dfbc4a9f1d037b75566b9eb1cc35cfc/src/core/core.c#L394

> I might prefer the prior less magical arrangement where vbank1 was always on top.

I agree this is a bit confusing, okay, let's go back to "vbank1 is always on top".

**Comment by nesbox** [comment]
I think it can be closed
