### ISSUE TITLE
The file system doesn't work in 0.70.1

### ISSUE THREAD

**Issue by planer28** [nesbox/TIC-80#664]
FOLDER command shows me the /documents directory, mkdir, config don't work.

**Comment by nesbox** [comment]
what os?
and what is your username in the system?
thanks

**Comment by nesbox** [comment]
I'm interested does your username in OS have non latin symbols?

**Comment by planer28** [comment]
Yes, "ł". But I didn't have any problems with it until this update.

**Comment by nesbox** [comment]
ok, I know how to fix this
will do with .70.2 hotfix
thanks

**Comment by nesbox** [comment]
fixed here f051c35

**Comment by Quentie** [comment]
ON OSX "folder"  command is completely gone? 
<img width="770" alt="screen shot 2018-08-19 at 21 28 35" src="https://user-images.githubusercontent.com/2254297/44312344-dd9aeb80-a3f6-11e8-9fe6-af687d188b0b.png">

**Comment by nesbox** [comment]
yes, `folder` was accidentally removed in 70.1 but restored here f051c35

**Comment by Quentie** [comment]
cool thanks

**Comment by planer28** [comment]
Uhm I just downloaded 0.70.2 and checked, and it still doesn't work, for me at least.

**Comment by nesbox** [comment]
another one fix 
@planer28 could you pls test it if not difficult [tic80_fs_fix.zip](https://github.com/nesbox/TIC-80/files/2319828/tic80_fs_fix.zip)
thanks

**Comment by planer28** [comment]
It seems to work! Thanks.
